package(default_visibility = ["//visibility:public"])

exports_files(["bazel_verilator_lint.sh",
               "bazel_verilator_binary.sh",
               "bazel_verilator_run.sh",
               "sim_main.cpp.template"])
