# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    container:
      # TODO(drewranck): there's probably a better way, but I had issues using
      # verilator/verilator:latest as a container and then using actions for
      # - uses: bazelbuild/setup-bazelisk@v2
      # - uses: actions/cache@v3
      # So instead, I'm uing my own container that has bazel and verilator in it,
      # with an entrypoint to /bin/bash:
      # Also we'll probably need to figure out why this container is missing zlib.h
      # which prevents me from running verilator with --trace
      image: drewranck/bazel_plus_verilator:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Bazel test the repo
        run: bazel test //...      
